version: '3'
services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - .:/app
    environment:
      - POSTGRES_PASSWORD=password
